;;-*-coding: utf-8;-*-

;; -*- coding: utf-8 -*-
;; emacs abbrev def
;; 〈Using Emacs Abbrev Mode for Abbreviation〉 http://ergoemacs.org/emacs/emacs_abbrev_mode.html

; load my abbreviations file
;(read-abbrev-file "emacs_abbrev")


(clear-abbrev-table global-abbrev-table)

(define-abbrev-table 'global-abbrev-table
  '(
    ("afaik" "As far as i know")
    ("ahd" "American Heritage Dictionary")
    ("ahk" "AutoHotkey")
    ("ai" "artificial intelligence")
    ("ann" "announcement")
    ("atm" "at the moment")
    ("autom" "automatic")
    ("bc" "because")
    ("bg" "background")
    ("bt" "between")
    ("btw" "by the way")
    ("bu" "•")
    ("catface" "😸")
    ("cfg" "context-free grammar")
    ("ch" "Chinese")
    ("cj" "Clojure")
    ("cl" "Common Lisp")
    ("cnt" "can't")
    ("comm" "communication")
    ("comp" "computer")
    ("cs" "computer science")
    ("da" "↓")
    ("ddnt" "didn't")
    ("desc" "description")
    ("dev" "development")
    ("dfb" "difference between")
    ("dict" "dictionary")
    ("dicts" "dictionaries")
    ("dir" "directory")
    ("dirs" "directories")
    ("disc" "discussion")
    ("dl" "download")
    ("dnt" "don't")
    ("dsnt" "doesn't")
    ("dvp" "develop")
    ("ee" "ErgoEmacs")
    ("eem" "ergoemacs-mode")
    ("eg" "e.g.")
    ("emoji" "😃😄😅😆
😉😊😋😌
😎😇😈
😁😂😀
😚😘😍😙😗
😛😜😝
😩😫😪😴
😏😓😔😖😐😑😕
😮😯😰😱😲😳😵😶😷
😒😠😡
😞😟😣😤😥😦😧😨😬
😢😭
😸😹😺😻😼😽😾😿🙀")
    ("eng" "English")
    ("env" "environment")
    ("esp" "especially")
    ("ev" "environment variable")
    ("evs" "environment variables")
    ("ex" "example")
    ("faq" "frequently asked questions")
    ("fb" "Facebook")
    ("fex" "for example,")
    ("fs" "fullscreen")
    ("fx" "Firefox")
    ("gc" "Google Chrome")
    ("gcd" "googlecode")
    ("ge" "Google Earth")
    ("gh" "Google Hangout")
    ("gm" "Google Map")
    ("gp" "Google Plus")
    ("gvn" "government")
    ("hearts" "♥💕💓💔💖💗💘💝💞💟💙💚💛💜")
    ("hex" "hexadecimal")
    ("hnt" "haven't")
    ("i18n" "international")
    ("ia" "interactive")
    ("ie" "Internet Explorer")
    ("impl" "implementation")
    ("implt" "implement")
    ("intro" "introduction")
    ("ipa" "IP address")
    ("ipv4" "IPv4")
    ("ipv6" "IPv6")
    ("isnt" "isn't")
    ("jp" "Japanese")
    ("jq" "jQuery")
    ("jvm" "Java Virtual Machine")
    ("kb" "keyboard")
    ("kbd" "keybinding")
    ("kbs" "keyboards")
    ("kw" "keyword")
    ("la" "←")
    ("lr" "#lang racket")
    ("lsl" "Linden Scripting Language")
    ("mac" "Mac")
    ("macosx" "Mac OS X")
    ("mma" "Mathematica")
    ("ms" "Microsoft")
    ("msvs" "Microsoft Visual Studio")
    ("msw" "Microsoft Windows")
    ("omg" "😂")
    ("osx" "OS X")
    ("paren" "parenthesis")
    ("pl" "programing language")
    ("pls" "please")
    ("pp" "PayPal")
    ("prof" "professor")
    ("ra" "→")
    ("ref" "reference")
    ("rsi" "Repetitive Strain Injury")
    ("sf" "San Francisco")
    ("shnt" "shouldn't")
    ("sl" "Second Life")
    ("ss" "screenshot")
    ("subdir" "sub-directory")
    ("subdirs" "sub-directories")
    ("techn" "technology")
    ("trad" "traditional")
    ("ty" "thank you")
    ("u3dxm" "http://3D-XplorMath.org/")
    ("ua" "↑")
    ("uahk" "http://xahlee.info/mswin/autohotkey.html")
    ("uapache" "http://xahlee.info/linux/apache_tutorial.html")
    ("ucss" "http://xahlee.info/js/css_index.html")
    ("udvorak" "http://xahlee.info/comp/dvorak_keyboard_layout.html")
    ("ueek" "http://ergoemacs.org/emacs/ergonomic_emacs_keybinding.html")
    ("uelisp" "http://ergoemacs.org/emacs/elisp.html")
    ("uem" "http://ergoemacs.github.io/")
    ("uemacs" "http://ergoemacs.org/emacs/emacs.html")
    ("uergodox" "http://xahlee.info/kbd/ergodox_keyboard.html")
    ("uhtml" "http://xahlee.info/js/html_index.html")
    ("ui" "user interface")
    ("ujava" "http://xahlee.info/java-a-day/java.html")
    ("ujs" "http://xahlee.info/js/javascript_basics.html")
    ("ukinesis" "http://xahlee.info/kbd/keyboard_Kinesis.html")
    ("ulang" "<a href=\"../java-a-day/java.html\">Java</a>
<a href=\"../python/python3_basics.html\">Python</a>
<a href=\"../ruby/ruby_basics.html\">Ruby</a>
<a href=\"../perl-python/perl_basics.html\">Perl</a>
<a href=\"../php/php_basics.html\">PHP</a>
<a href=\"http://ergoemacs.org/emacs/elisp.html\">Emacs Lisp</a>")
    ("umaltron" "http://xahlee.info/kbd/Maltron_keyboard.html")
    ("umma" "http://xahlee.info/M/index.html")
    ("uns" "understand")
    ("uocaml" "http://xahlee.info/ocaml/ocaml.html")
    ("uperl" "http://xahlee.info/perl-python/perl_basics.html")
    ("uphp" "http://xahlee.info/php/php_basics.html")
    ("ups" "http://xahlee.info/powershell/index.html")
    ("upython" "http://xahlee.info/python/python3_basics.html")
    ("ur" "you are")
    ("uruby" "http://xahlee.info/ruby/ruby_basics.html")
    ("ute" "http://xahlee.info/kbd/Truly_Ergonomic_keyboard.html")
    ("utek" "http://xahlee.info/kbd/Truly_Ergonomic_keyboard.html")
    ("utg" "http://xahlee.info/UnixResource_dir/writ/tech_geeker.html")
    ("uunicode" "http://xahlee.info/comp/unicode_index.html")
    ("uutron" "http://xahlee.info/kbd/uTRON_keyboard.html")
    ("uvi" "http://ergoemacs.org/emacs/emergency_vi.html")
    ("uvmm" "http://VirtualMathMuseum.org/")
    ("uwd" "http://xahlee.info/js/index.html")
    ("uwe" "http://wordyenglish.com/")
    ("uxa" "http://xaharts.org/")
    ("uxl" "http://xahlee.org/")
    ("uxli" "http://xahlee.info/")
    ("uxm" "http://xahmusic.org/")
    ("uxp" "http://xahporn.org/")
    ("uxsl" "http://xahsl.org/")
    ("vb" "Visual Basic")
    ("vdspc" "Visual Dictionary of Special Plane Curves")
    ("ver" "version")
    ("vid" "video")
    ("wd" "web development")
    ("win" "window")
    ("wl" "Wolfram Language")
    ("wm" "Window Manager")
    ("wnt" "won't")
    ("wp" "Wikipedia")
    ("wsnt" "wasn't")
    ("wtdb" "What's the difference between")
    ("www" "whatthefucklongword")
    ("xfk" "xah-fly-keys")
    ("xim" "Twitter: @xah_lee
Facebook: https://www.facebook.com/xahlee
g+: https://plus.google.com/112757647855302148298/posts
Google talk: xahlee@gmail.com
Skype: XahLee
AIM: xahlee
Yahoo: P0lyglut
MSN: p0lyglut@yahoo.com or xahlee
Second Life: Xah Toll
QQ: http://user.qzone.qq.com/2609322939")
    ("xl" "Xah Lee")
    ("xs" " Xah Lee
 xahlee@gmail.com
 http://xahlee.org/
 US citizen.
 Mountain View, CA.")
    ("yt" "YouTube")
    ("zalt" "alternative")
    ("zarrows" "➵➙►▻☛☞👉⇰➛➜➝➞➟➠➢➣➤➥➦➧➨➲➺➻➼➽➾")
    ("zascii" "!\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~")
    ("zauto" "automatic")
    ("zaz" "\\([A-Za-z0-9]+\\)")
    ("zbox" "┌─┬─┐
│ │ │
├─┼─┤
│ │ │
└─┴─┘")
    ("zbracket" "\\[\\([^]]+?\\)\\]")
    ("zc" "character")
    ("zca" "cellular automata")
    ("zchars" "characters")
    ("zcli" "command line interface")
    ("zcurly" "“\\([^”]+?\\)”")
    ("zd" "\\([0-9]+\\)")
    ("zdate" "\\([0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\\)")
    ("zdb" "database")
    ("zdef" "definition")
    ("zdf" "different")
    ("zdfc" "difference")
    ("zdoc" "documentation")
    ("zdot" "\\(.\\)")
    ("zdt" "data type")
    ("ze" "emacs")
    ("zel" "emacs lisp")
    ("zergo" "ergonomic")
    ("zexp" "experience")
    ("zexpr" "expression")
    ("zf" "function")
    ("zfaq" "<div class=\"question-box32371\">
<p class=\"q\">How to do this?</p>
<p>this way</p>
</div>\n\n")
    ("zfl" "functional language")
    ("zfp" "functional programing")
    ("zg" "Google")
    ("zgui" "graphical user interface")
    ("zis" "image source")
    ("zit" "IntelliType")
    ("zjs" "JavaScript")
    ("zkey" "【Alt+f】")
    ("zl" "language")
    ("zlhs" "left-hand-side")
    ("zlib" "library")
    ("zlibs" "libraries")
    ("zmath" "mathematics")
    ("zmd" "metadata")
    ("zmenu" "〖a ▸ b ▸ c〗")
    ("zoop" "object oriented programing")
    ("zorg" "organization")
    ("zos" "operating system")
    ("zp" "program")
    ("zphp" "<?php\n\n?>")
    ("zpm" "parameter")
    ("zprog" "programing")
    ("zps" "PowerShell")
    ("zq" "question")
    ("zrhs" "right-hand-side")
    ("zs" "string")
    ("zsc" "source code")
    ("zsjw" "social justice warriors")
    ("zso" "StackOverflow")
    ("zsong" "singer ♪《title》")
    ("zstr" "\\([^\"]+?\\)")
    ("ztag" "\\([</>=\" A-Za-z0-9]+\\)")
    ("ztek" "Truly Ergonomic keyboard")
    ("ztemp" "temperature")
    ("zutf8" "-*- coding: utf-8 -*-")
    ("zv" "variable")
    ("zvs" "variables")
   ))

;; (abbrev-table-put global-abbrev-table :case-fixed t)
