;; -*- coding: utf-8 -*-
;; xah's emacs keybinding.

(progn
  (global-set-key (kbd "<menu> g") 'nil)
  (global-set-key (kbd "<menu> g '") "\"")
  (global-set-key (kbd "<menu> g ,") "<")
  (global-set-key (kbd "<menu> g -") "_")
  (global-set-key (kbd "<menu> g .") ">")
  (global-set-key (kbd "<menu> g /") "?")
  (global-set-key (kbd "<menu> g ;") ":")
  (global-set-key (kbd "<menu> g =") "+")
  (global-set-key (kbd "<menu> g \\") "|")
  (global-set-key (kbd "<menu> g `") "~")

  (global-set-key (kbd "<menu> g 0") ")")
  (global-set-key (kbd "<menu> g 1") "!")
  (global-set-key (kbd "<menu> g 2") "@")
  (global-set-key (kbd "<menu> g 3") "#")
  (global-set-key (kbd "<menu> g 4") "$")
  (global-set-key (kbd "<menu> g 5") "%")
  (global-set-key (kbd "<menu> g 6") "^")
  (global-set-key (kbd "<menu> g 7") "&")
  (global-set-key (kbd "<menu> g 8") "*")
  (global-set-key (kbd "<menu> g 9") "(")

  (global-set-key (kbd "<menu> g a") "A")
  (global-set-key (kbd "<menu> g b") "B")
  (global-set-key (kbd "<menu> g c") "C")
  (global-set-key (kbd "<menu> g d") "D")
  (global-set-key (kbd "<menu> g e") "E")
  (global-set-key (kbd "<menu> g f") "F")
  (global-set-key (kbd "<menu> g g") "G")
  (global-set-key (kbd "<menu> g h") "H")
  (global-set-key (kbd "<menu> g i") "I")
  (global-set-key (kbd "<menu> g j") "J")
  (global-set-key (kbd "<menu> g k") "K")
  (global-set-key (kbd "<menu> g l") "L")
  (global-set-key (kbd "<menu> g m") "M")
  (global-set-key (kbd "<menu> g n") "N")
  (global-set-key (kbd "<menu> g o") "O")
  (global-set-key (kbd "<menu> g p") "P")
  (global-set-key (kbd "<menu> g q") "Q")
  (global-set-key (kbd "<menu> g r") "R")
  (global-set-key (kbd "<menu> g s") "S")
  (global-set-key (kbd "<menu> g t") "T")
  (global-set-key (kbd "<menu> g u") "U")
  (global-set-key (kbd "<menu> g v") "V")
  (global-set-key (kbd "<menu> g w") "W")
  (global-set-key (kbd "<menu> g x") "X")
  (global-set-key (kbd "<menu> g y") "Y")
  (global-set-key (kbd "<menu> g z") "Z")
  )
