;; -*- coding: utf-8 -*-

;; (global-unset-key (kbd "<f1>") )
;; (global-unset-key (kbd "<f2>") )
;; (global-unset-key (kbd "<f3>") )
;; (global-unset-key (kbd "<f4>") )
;; (global-unset-key (kbd "<f5>") )
;; (global-unset-key (kbd "<f6>") )
;; (global-unset-key (kbd "<f7>") )
;; (global-unset-key (kbd "<f8>") )
;; (global-unset-key (kbd "<f9>") )
;; (global-unset-key (kbd "<f10>") )
;; (global-unset-key (kbd "<f11>") )
;; (global-unset-key (kbd "<f12>") )

(global-unset-key (kbd "<kp-0>") )
(global-unset-key (kbd "<kp-1>") )
(global-unset-key (kbd "<kp-2>") )
(global-unset-key (kbd "<kp-3>") )
(global-unset-key (kbd "<kp-4>") )
(global-unset-key (kbd "<kp-5>") )
(global-unset-key (kbd "<kp-6>") )
(global-unset-key (kbd "<kp-7>") )
(global-unset-key (kbd "<kp-8>") )
(global-unset-key (kbd "<kp-9>") )

(global-unset-key (kbd "<C-kp-0>") )
(global-unset-key (kbd "<C-kp-1>") )
(global-unset-key (kbd "<C-kp-2>") )
(global-unset-key (kbd "<C-kp-3>") )
(global-unset-key (kbd "<C-kp-4>") )
(global-unset-key (kbd "<C-kp-5>") )
(global-unset-key (kbd "<C-kp-6>") )
(global-unset-key (kbd "<C-kp-7>") )
(global-unset-key (kbd "<C-kp-8>") )
(global-unset-key (kbd "<C-kp-9>") )
