;; -*- coding: utf-8 -*-
;; xah's emacs keybinding.

(define-key key-translation-map (kbd "<menu> SPC SPC") (kbd "_")) ;low line (underscore)
(define-key key-translation-map (kbd "<menu> SPC RET") (kbd "-"))

(progn
  (define-key key-translation-map (kbd "<menu> SPC '") (kbd "\""))
  (define-key key-translation-map (kbd "<menu> SPC ,") (kbd "<"))
  (define-key key-translation-map (kbd "<menu> SPC -") (kbd "_"))
  (define-key key-translation-map (kbd "<menu> SPC .") (kbd ">"))
  (define-key key-translation-map (kbd "<menu> SPC /") (kbd "?"))
  (define-key key-translation-map (kbd "<menu> SPC ;") (kbd ":"))
  (define-key key-translation-map (kbd "<menu> SPC =") (kbd "+"))
  (define-key key-translation-map (kbd "<menu> SPC \\") (kbd "|"))
  (define-key key-translation-map (kbd "<menu> SPC `") (kbd "~"))

  (define-key key-translation-map (kbd "<menu> SPC 0") (kbd ")"))
  (define-key key-translation-map (kbd "<menu> SPC 1") (kbd "!"))
  (define-key key-translation-map (kbd "<menu> SPC 2") (kbd "@"))
  (define-key key-translation-map (kbd "<menu> SPC 3") (kbd "#"))
  (define-key key-translation-map (kbd "<menu> SPC 4") (kbd "$"))
  (define-key key-translation-map (kbd "<menu> SPC 5") (kbd "%"))
  (define-key key-translation-map (kbd "<menu> SPC 6") (kbd "^"))
  (define-key key-translation-map (kbd "<menu> SPC 7") (kbd "&"))
  (define-key key-translation-map (kbd "<menu> SPC 8") (kbd "*"))
  (define-key key-translation-map (kbd "<menu> SPC 9") (kbd "("))

  (define-key key-translation-map (kbd "<menu> SPC a") (kbd "A"))
  (define-key key-translation-map (kbd "<menu> SPC b") (kbd "B"))
  (define-key key-translation-map (kbd "<menu> SPC c") (kbd "C"))
  (define-key key-translation-map (kbd "<menu> SPC d") (kbd "D"))
  (define-key key-translation-map (kbd "<menu> SPC e") (kbd "E"))
  (define-key key-translation-map (kbd "<menu> SPC f") (kbd "F"))
  (define-key key-translation-map (kbd "<menu> SPC g") (kbd "G"))
  (define-key key-translation-map (kbd "<menu> SPC h") (kbd "H"))
  (define-key key-translation-map (kbd "<menu> SPC i") (kbd "I"))
  (define-key key-translation-map (kbd "<menu> SPC j") (kbd "J"))
  (define-key key-translation-map (kbd "<menu> SPC k") (kbd "K"))
  (define-key key-translation-map (kbd "<menu> SPC l") (kbd "L"))
  (define-key key-translation-map (kbd "<menu> SPC m") (kbd "M"))
  (define-key key-translation-map (kbd "<menu> SPC n") (kbd "N"))
  (define-key key-translation-map (kbd "<menu> SPC o") (kbd "O"))
  (define-key key-translation-map (kbd "<menu> SPC p") (kbd "P"))
  (define-key key-translation-map (kbd "<menu> SPC q") (kbd "Q"))
  (define-key key-translation-map (kbd "<menu> SPC r") (kbd "R"))
  (define-key key-translation-map (kbd "<menu> SPC s") (kbd "S"))
  (define-key key-translation-map (kbd "<menu> SPC t") (kbd "T"))
  (define-key key-translation-map (kbd "<menu> SPC u") (kbd "U"))
  (define-key key-translation-map (kbd "<menu> SPC v") (kbd "V"))
  (define-key key-translation-map (kbd "<menu> SPC w") (kbd "W"))
  (define-key key-translation-map (kbd "<menu> SPC x") (kbd "X"))
  (define-key key-translation-map (kbd "<menu> SPC y") (kbd "Y"))
  (define-key key-translation-map (kbd "<menu> SPC z") (kbd "Z"))
  )
