

(setq xfiles '(
"/home/xah/web/xahlee_info/js/DOM_img.html"
"/home/xah/web/xahlee_info/js/backbone_tutorial.html"
"/home/xah/web/xahlee_info/js/blog.html"
"/home/xah/web/xahlee_info/js/build_nodejs_doc.html"
"/home/xah/web/xahlee_info/js/content_change.html"
"/home/xah/web/xahlee_info/js/css_change.html"
"/home/xah/web/xahlee_info/js/css_index.html"
"/home/xah/web/xahlee_info/js/dom_common_dom_methods.html"
"/home/xah/web/xahlee_info/js/dom_window_popup.html"
"/home/xah/web/xahlee_info/js/event_sample.html"
"/home/xah/web/xahlee_info/js/events.html"
"/home/xah/web/xahlee_info/js/gettime.html"
"/home/xah/web/xahlee_info/js/google-code-prettify/index.html"
"/home/xah/web/xahlee_info/js/goto_url_new_window.html"
"/home/xah/web/xahlee_info/js/html5_canvas_vs_SVG.html"
"/home/xah/web/xahlee_info/js/html_form_sample.html"
"/home/xah/web/xahlee_info/js/index.html"
"/home/xah/web/xahlee_info/js/inline_svg_test_page.html"
"/home/xah/web/xahlee_info/js/ins_content.html"
"/home/xah/web/xahlee_info/js/javascript_basics.html"
"/home/xah/web/xahlee_info/js/javascript_call_function_as_method.html"
"/home/xah/web/xahlee_info/js/javascript_class_attribute.html"
"/home/xah/web/xahlee_info/js/javascript_closure.html"
"/home/xah/web/xahlee_info/js/javascript_determine_strict_mode.html"
"/home/xah/web/xahlee_info/js/javascript_dot_notation_vs_bracket_notation.html"
"/home/xah/web/xahlee_info/js/javascript_function_constructor.html"
"/home/xah/web/xahlee_info/js/javascript_function_this_keyword.html"
"/home/xah/web/xahlee_info/js/javascript_instanceof.html"
"/home/xah/web/xahlee_info/js/javascript_lang_fun.html"
"/home/xah/web/xahlee_info/js/javascript_name_hoisting_declaration_order.html"
"/home/xah/web/xahlee_info/js/javascript_name_hosting_and_one-liner_functional_style.html"
"/home/xah/web/xahlee_info/js/javascript_object_extensible.html"
"/home/xah/web/xahlee_info/js/javascript_property_and_prototype_chain.html"
"/home/xah/web/xahlee_info/js/javascript_property_attributes.html"
"/home/xah/web/xahlee_info/js/javascript_property_existence.html"
"/home/xah/web/xahlee_info/js/javascript_random_number.html"
"/home/xah/web/xahlee_info/js/javascript_var_scope.html"
"/home/xah/web/xahlee_info/js/javascript_whats_object.html"
"/home/xah/web/xahlee_info/js/jquery_tutorial.html"
"/home/xah/web/xahlee_info/js/js.html"
"/home/xah/web/xahlee_info/js/js_JavaScript_minecraft.html"
"/home/xah/web/xahlee_info/js/js_JavaScript_object_tutorial.html"
"/home/xah/web/xahlee_info/js/js_array_methods.html"
"/home/xah/web/xahlee_info/js/js_array_vs_nodelist_vs_html_collection.html"
"/home/xah/web/xahlee_info/js/js_browser_info.html"
"/home/xah/web/xahlee_info/js/js_canvas_halma.html"
"/home/xah/web/xahlee_info/js/js_canvas_raycaster.html"
"/home/xah/web/xahlee_info/js/js_canvas_tutorial.html"
"/home/xah/web/xahlee_info/js/js_convert_between_string_and_number.html"
"/home/xah/web/xahlee_info/js/js_cookies.html"
"/home/xah/web/xahlee_info/js/js_creating_object.html"
"/home/xah/web/xahlee_info/js/js_d3_rotating_voronoi_demo.html"
"/home/xah/web/xahlee_info/js/js_dollar_sign_in_javascript.html"
"/home/xah/web/xahlee_info/js/js_encode_url.html"
"/home/xah/web/xahlee_info/js/js_executing_order.html"
"/home/xah/web/xahlee_info/js/js_fadeout.html"
"/home/xah/web/xahlee_info/js/js_fadeout_css_transition.html"
"/home/xah/web/xahlee_info/js/js_form_validation.html"
"/home/xah/web/xahlee_info/js/js_form_validation2.html"
"/home/xah/web/xahlee_info/js/js_get_attributes.html"
"/home/xah/web/xahlee_info/js/js_get_elements.html"
"/home/xah/web/xahlee_info/js/js_get_node_info.html"
"/home/xah/web/xahlee_info/js/js_get_url.html"
"/home/xah/web/xahlee_info/js/js_getter_and_setter_properties.html"
"/home/xah/web/xahlee_info/js/js_insert_after.html"
"/home/xah/web/xahlee_info/js/js_insert_js_code.html"
"/home/xah/web/xahlee_info/js/js_keyword_new.html"
"/home/xah/web/xahlee_info/js/js_map_forEach.html"
"/home/xah/web/xahlee_info/js/js_molecules_demo.html"
"/home/xah/web/xahlee_info/js/js_navigate_nodes.html"
"/home/xah/web/xahlee_info/js/js_object_prototype_inheritance.html"
"/home/xah/web/xahlee_info/js/js_prototype.html"
"/home/xah/web/xahlee_info/js/js_regex.html"
"/home/xah/web/xahlee_info/js/js_regex_methods.html"
"/home/xah/web/xahlee_info/js/js_regex_syntax.html"
"/home/xah/web/xahlee_info/js/js_scritping_svg_basics.html"
"/home/xah/web/xahlee_info/js/js_set_attribute.html"
"/home/xah/web/xahlee_info/js/js_shake_box.html"
"/home/xah/web/xahlee_info/js/js_stopwatch.html"
"/home/xah/web/xahlee_info/js/js_string_byte_sequence.html"
"/home/xah/web/xahlee_info/js/js_string_methods.html"
"/home/xah/web/xahlee_info/js/js_string_number_not_object_but_methods.html"
"/home/xah/web/xahlee_info/js/js_trick_exclamation_before_function.html"
"/home/xah/web/xahlee_info/js/js_unicode_code_point.html"
"/home/xah/web/xahlee_info/js/js_unicode_escape_sequence.html"
"/home/xah/web/xahlee_info/js/js_unicode_in_identifiers.html"
"/home/xah/web/xahlee_info/js/js_web_storage.html"
"/home/xah/web/xahlee_info/js/moving_block.html"
"/home/xah/web/xahlee_info/js/print.html"
"/home/xah/web/xahlee_info/js/svg_path_spec.html"
"/home/xah/web/xahlee_info/js/svg_viewBox.html"
"/home/xah/web/xahlee_info/js/tabs/a.html"
"/home/xah/web/xahlee_info/js/tooltips.html"
) )

(defun my-process-file (fPath)
  "Process the file at path FPATH …"
  (with-temp-buffer
    (insert-file-contents fPath)
    (xah-html-redo-syntax-coloring-buffer)
    (write-region 1 (point-max) fPath)))

(require 'find-lisp)

(mapc 'my-process-file xfiles)

;; (mapc 'my-process-file (find-lisp-find-files "/home/xah/web/xahlee_info/js/" "\\.html$"))

;; (insert-file-contents "javascript_class_attribute.html")